# Generated by Django 6.1.1 on 2026-09-24 22:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('daily_hours_limit', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)])),
                ('user_type', models.CharField(default='organizador', max_length=50)),
            ],
            options={
                'db_table': 'api_organizer',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('event_type', models.CharField(choices=[('boda', 'Boda'), ('social', 'Social'), ('corporativo', 'Corporativo'), ('cumpleanos', 'Cumpleaños'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('client_contact', models.CharField(max_length=150)),
                ('event_date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.organizer')),
            ],
            options={
                'db_table': 'api_event',
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('due_date', models.DateField()),
                ('estimated_hours', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('state', models.CharField(choices=[('pendiente', 'Pendiente'), ('hecha', 'Hecha'), ('pospuesta', 'Pospuesta')], default='pendiente', max_length=20)),
                ('type', models.CharField(choices=[('task', 'Tarea'), ('subtask', 'Subtarea')], default='task', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.event')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.organizer')),
                ('parent', models.ForeignKey(blank=True, db_column='group_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='api.task')),
            ],
            options={
                'db_table': 'api_task',
                'ordering': ['due_date'],
            },
        ),
    ]
