# Generated by Django 6.1.1 on 2026-09-25 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_estimated_hours'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('parent__isnull', True), ('type', 'task')), models.Q(('parent__isnull', False), ('type', 'subtask')), _connector='OR'), name='task_type_parent_consistency'),
        ),
    ]
