# Generated by Django 6.1.1 on 2026-09-25 02:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_task_task_type_parent_consistency'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='organizer',
            constraint=models.CheckConstraint(condition=models.Q(('daily_hours_limit__gte', 1), ('daily_hours_limit__lte', 16)), name='organizer_daily_hours_limit_range'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('estimated_hours__gte', Decimal('0.1'))), name='task_estimated_hours_positive'),
        ),
    ]
