# Generated by Django 6.1.1

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_event_users_and_profiles(apps, schema_editor):
    """Asigna Event.user desde Organizer.user (o crea un User inactivo).

    También crea Profile para usuarios existentes, copiando el nombre del
    Organizer cuando existe. No borra datos; el reverse no elimina usuarios.
    """
    User = apps.get_model("auth", "User")
    Organizer = apps.get_model("api", "Organizer")
    Event = apps.get_model("api", "Event")
    Profile = apps.get_model("api", "Profile")

    event_organizer_ids = Event.objects.order_by().values_list("organizer_id", flat=True)
    for organizer in Organizer.objects.filter(pk__in=event_organizer_ids):
        if organizer.user_id:
            continue
        username = f"organizador_{organizer.id}"
        user, created = User.objects.get_or_create(
            username=username,
            defaults={
                "is_active": False,
                "password": "!",
            },
        )
        if created:
            user.is_active = False
            user.password = "!"
            user.save()
        organizer.user_id = user.id
        organizer.save(update_fields=["user_id"])

    for event in Event.objects.all():
        if event.user_id:
            continue
        if event.organizer_id and event.organizer.user_id:
            event.user_id = event.organizer.user_id
            event.save(update_fields=["user_id"])

    for user in User.objects.all():
        if Profile.objects.filter(user_id=user.id).exists():
            profile = Profile.objects.get(user_id=user.id)
            if profile.full_name:
                continue
            organizer = Organizer.objects.filter(user_id=user.id).first()
            if organizer:
                profile.full_name = f"{organizer.name} {organizer.last_name}".strip()
                profile.save(update_fields=["full_name"])
            continue
        full_name = ""
        organizer = Organizer.objects.filter(user_id=user.id).first()
        if organizer:
            full_name = f"{organizer.name} {organizer.last_name}".strip()
        Profile.objects.create(user_id=user.id, full_name=full_name)


def noop_reverse(apps, schema_editor):
    """No destructivo: no borra usuarios ni perfiles creados al migrar."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_organizer_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="events",
                to="api.organizer",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="organizer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="api.organizer",
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("full_name", models.CharField(blank=True, max_length=150)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("document_number", models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "api_profile",
            },
        ),
        migrations.RunPython(backfill_event_users_and_profiles, noop_reverse),
        migrations.AlterField(
            model_name="event",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
