# Generated by Django 6.1.1 on 2026-10-07 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_event_user_profile_and_ownership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='document_number',
        ),
    ]
