-- =========================================
-- Esquema de organizadores, eventos y tareas logisticas
--
-- Fuente de verdad real: las migraciones de Django en
-- backend/api/migrations/ (se aplican con `python manage.py migrate`
-- contra DATABASE_URL). Este archivo es un espejo en SQL plano de ese
-- mismo esquema, para quien prefiera leerlo asi o para levantar una
-- instancia local con el CLI de Supabase (`supabase db reset`).
--
-- Si el modelo de Django cambia (nuevo campo, constraint, etc.), hay
-- que regenerar este archivo tambien; se puede obtener el SQL exacto
-- de una migracion con `python manage.py sqlmigrate api <numero>`.
-- =========================================

CREATE TABLE api_organizer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    daily_hours_limit SMALLINT NOT NULL CHECK (daily_hours_limit >= 1 AND daily_hours_limit <= 16),
    user_type VARCHAR(50) NOT NULL
);

CREATE TABLE api_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    event_type VARCHAR(30) NOT NULL,
    client_contact VARCHAR(150) NOT NULL,
    event_date TIMESTAMPTZ NOT NULL,
    location VARCHAR(200) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    organizer_id BIGINT NOT NULL
        CONSTRAINT api_event_organizer_id_e13d0573_fk_api_organizer_id
        REFERENCES api_organizer (id) DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX api_event_organizer_id_e13d0573 ON api_event (organizer_id);

CREATE TABLE api_task (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(500) NOT NULL,
    due_date DATE NOT NULL,
    estimated_hours NUMERIC(5, 2) NOT NULL,
    state VARCHAR(20) NOT NULL,
    type VARCHAR(20) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    event_id BIGINT NOT NULL
        CONSTRAINT api_task_event_id_ac6c9147_fk_api_event_id
        REFERENCES api_event (id) DEFERRABLE INITIALLY DEFERRED,
    organizer_id BIGINT NOT NULL
        CONSTRAINT api_task_organizer_id_03c1f53d_fk_api_organizer_id
        REFERENCES api_organizer (id) DEFERRABLE INITIALLY DEFERRED,
    -- group_id: referencia a la tarea padre (self-FK). NULL cuando
    -- type='task' (gestion de nivel superior); obligatorio cuando
    -- type='subtask' (paso dentro de una tarea). Ver constraint abajo.
    group_id BIGINT NULL
        CONSTRAINT api_task_group_id_5890abf2_fk_api_task_id
        REFERENCES api_task (id) DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT task_type_parent_consistency CHECK (
        (group_id IS NULL AND type = 'task') OR (group_id IS NOT NULL AND type = 'subtask')
    )
);

CREATE INDEX api_task_event_id_ac6c9147 ON api_task (event_id);
CREATE INDEX api_task_organizer_id_03c1f53d ON api_task (organizer_id);
CREATE INDEX api_task_group_id_5890abf2 ON api_task (group_id);
